name: Containers

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: frontend
            dockerfile: configs/docker/frontend.Dockerfile
            context: .
            image: blockbuilders/frontend-dev
          - name: backend
            dockerfile: configs/docker/backend.Dockerfile
            context: .
            image: blockbuilders/backend-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: false
          tags: ${{ matrix.service.image }}:ci
          cache-from: type=gha,scope=${{ matrix.service.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service.name }}

      - name: Scan ${{ matrix.service.name }} image (Trivy)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ matrix.service.image }}:ci
          severity: CRITICAL,HIGH
          format: table
