model = "gpt-5-codex"
model_reasoning_effort = "medium"

[projects."/Users/pierrickmartino/Developer/blockbuilders.tech.speckit"]
trust_level = "trusted"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-7b167dbc-5284-4af5-b51d-431a0818dc12"]
command = "npx"