import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  designTokens,
  getCssVariableName,
} from '../lib/design-system/tokens';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const stylesDir = path.resolve(__dirname, '../styles');
const outputPath = path.join(stylesDir, 'tokens.css');

function formatVariables(): { light: string[]; dark: string[] } {
  return designTokens.reduce(
    (acc, token) => {
      const variableName = getCssVariableName(token);
      acc.light.push(`  ${variableName}: ${token.value};`);
      acc.dark.push(`  ${variableName}: ${token.darkValue ?? token.value};`);
      return acc;
    },
    { light: [], dark: [] } as { light: string[]; dark: string[] },
  );
}

function buildStylesheet(): string {
  const { light, dark } = formatVariables();
  const banner =
    '/* This file is auto-generated by pnpm --filter @blockbuilders/frontend... run tokens:build */';

  return [
    banner,
    ':root,',
    "[data-theme='light'] {",
    light.join('\n'),
    '}',
    '',
    "[data-theme='dark'] {",
    dark.join('\n'),
    '}',
    '',
  ]
    .filter(Boolean)
    .join('\n');
}

function writeStylesheet(): void {
  fs.mkdirSync(stylesDir, { recursive: true });
  fs.writeFileSync(outputPath, `${buildStylesheet()}\n`);
  console.log(`✓ Design tokens written to ${path.relative(process.cwd(), outputPath)}`);
}

writeStylesheet();
